// */netlify/functions/test-function.ts

import { Handler, HandlerEvent, HandlerContext } from "@netlify/functions";

const handler: Handler = async (event: HandlerEvent, context: HandlerContext) => {
    console.log("Received event:", event);

    return {
        statusCode: 200,
    };
};

export { handler };

[[plugins]]
  package = "@takeshape/netlify-plugin-takeshape"

  # Optional: specify the timzeone for your TakeShape project (defaults to "America/New_York")
  [plugins.inputs]
    timezone = "America/Los_Angeles"
